import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  ${inter.className}`}>
        <ToastContainer />
        <div className="flex flex-col min-h-screen justify-between">
          {children}
          <div
            style={{
              width: "100%",
            }}
          >
            <Image
              src="/svgs/footer-wave.svg"
              alt="Footer SVG"
              width={200}
              height={50}
              style={{
                width: "100%",
              }}
            />
          </div>
        </div>
      </body>
    </html>
  );
}
